# site settings

title: Qindan Zhu
description: 
taglong: I synthesize field observations, remote sensing, model simulations, and machine learning to study urban air quality and chemistry-climate interaction
tagshort: I study urban air quality and chemistry-climate interaction
url: https://qindanzhu.com
baseurl: ""
permalink: pretty
repo: https://github.com/qdzhu/qdzhu.github.io

# author settings

author:
  name: Qindan Zhu
  email: qdzhu@mit.edu
photo: /assets/jpg/headshot.JPG

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
